/**
 * Documentation URL configuration module.
 * Reads the documentation URL from environment variable at runtime.
 *
 * Generated by /docgen skill.
 */

// Environment variable name for docs URL
const DOCS_ENV_VAR = 'ECML_DOCS_URL';

// Default fallback URL (local Docker instance)
const DEFAULT_DOCS_URL = 'http://localhost:4000';

/**
 * Gets the documentation base URL from environment or falls back to default.
 */
export function getDocsUrl(): string {
    // In browser context, env vars are typically injected at build time
    // or via window object. Check both patterns.
    const envUrl = (globalThis as Record<string, unknown>)[DOCS_ENV_VAR] as string | undefined
        ?? (typeof process !== 'undefined' ? process.env?.[DOCS_ENV_VAR] : undefined);

    return envUrl || DEFAULT_DOCS_URL;
}

/**
 * Documentation URL paths for IDE integration.
 */
export const DocsUrls = {
    /** Home page */
    home: (): string => getDocsUrl(),
    /** Getting started guide */
    gettingStarted: (): string => `${getDocsUrl()}/getting-started/`,
    /** User guide */
    userGuide: (): string => `${getDocsUrl()}/guide/`,
    /** Language reference */
    languageReference: (): string => `${getDocsUrl()}/language/`,
    /** Examples */
    examples: (): string => `${getDocsUrl()}/examples/`,
} as const;

/** Environment variable name for external configuration */
export const DOCS_ENV_VAR_NAME = DOCS_ENV_VAR;
