/**
 * Example Minimal Language Contribution
 *
 * Demonstrates the contribution pattern for SANYAM integration.
 *
 * @packageDocumentation
 */

import type {
  LanguageContributionInterface,
  LspFeatureProviders,
  GlspFeatureProviders,
} from '@sanyam/types';

import { manifest } from './manifest.js';

/**
 * Custom LSP providers for example-minimal.
 *
 * This example shows how to add custom completion items.
 */
const customLspProviders: Partial<LspFeatureProviders> = {
  // Example: Add keyword completions
  // completion: {
  //   provide: async (document, position, context) => {
  //     return [
  //       { label: 'box', kind: 14, detail: 'Create a new box' },
  //       { label: 'arrow', kind: 14, detail: 'Create an arrow' },
  //     ];
  //   },
  // },
};

/**
 * Custom GLSP providers for example-minimal.
 *
 * This example uses the default providers.
 */
const customGlspProviders: Partial<GlspFeatureProviders> = {
  // Default providers are used
};

/**
 * Example Minimal Language Contribution
 *
 * This is the main export that the unified server discovers and loads.
 * Note: This is a minimal example without generated Langium modules.
 * For full integration, run `langium generate` and import the generated modules.
 */
export const contribution: LanguageContributionInterface = {
  languageId: 'example-minimal',
  fileExtensions: ['.exm', '.example'],
  // Placeholder modules - in a real grammar these would be generated by Langium
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  generatedSharedModule: {} as any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  generatedModule: {} as any,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  manifest: manifest as any,
  lspProviders: customLspProviders,
  glspProviders: customGlspProviders,
};

export default contribution;
