/**
 * Generate Bicep Operation
 *
 * Generate Azure Bicep infrastructure-as-code for deploying
 * the content model to Microsoft 365/Azure.
 *
 * @packageDocumentation
 */

import type { OperationHandler, OperationContext, OperationResult } from '@sanyam/types';

/**
 * Handler for Generate Bicep.
 *
 * Target types: ContentModel, SecurityGroup
 */
export const generateBicepHandler: OperationHandler = async (
  context: OperationContext
): Promise<OperationResult> => {
  const { document, selectedIds } = context;
  const ast = document.parseResult.value as any;

  if (!ast) {
    return {
      success: false,
      error: 'Failed to parse document',
    };
  }

  const bicep = generateBicepTemplate(ast, selectedIds);

  return {
    success: true,
    data: {
      bicep,
      fileName: 'content-model.bicep',
    },
    message: 'Bicep template generated successfully',
  };
};

/**
 * Generate Bicep template from AST.
 */
function generateBicepTemplate(ast: any, selectedIds?: readonly string[]): string {
  const lines: string[] = [];

  // Header
  lines.push('// Generated by ECML - Enterprise Content Modeling Language');
  lines.push('// This Bicep template deploys content model resources to Azure/M365');
  lines.push('');
  lines.push("targetScope = 'subscription'");
  lines.push('');

  // Parameters
  lines.push('// Parameters');
  lines.push("@description('Environment name (dev, staging, prod)')");
  lines.push("param environment string = 'dev'");
  lines.push('');
  lines.push("@description('Location for resources')");
  lines.push("param location string = 'eastus'");
  lines.push('');
  lines.push("@description('SharePoint site URL')");
  lines.push('param siteUrl string');
  lines.push('');

  // Variables
  lines.push('// Variables');
  lines.push("var resourcePrefix = 'ecml-${environment}'");
  lines.push('');

  // Resource Group
  lines.push('// Resource Group for ECML resources');
  lines.push("resource rg 'Microsoft.Resources/resourceGroups@2023-07-01' = {");
  lines.push("  name: '${resourcePrefix}-rg'");
  lines.push('  location: location');
  lines.push('  tags: {');
  lines.push("    application: 'ecml'");
  lines.push('    environment: environment');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Collect security groups
  const securityGroups = (ast.statements ?? []).filter(
    (s: any) => s.$type === 'SecurityGroup' && (!selectedIds?.length || selectedIds.includes(s.name))
  );

  if (securityGroups.length > 0) {
    lines.push('// Security Groups (Azure AD Groups)');
    lines.push('// Note: Azure AD group creation requires Graph API');
    lines.push('// The following is a reference for deployment scripts');
    lines.push('/*');
    for (const sg of securityGroups) {
      const title = sg.title?.replace(/^["']|["']$/g, '') ?? sg.name;
      const description = sg.description?.replace(/^["']|["']$/g, '') ?? '';
      lines.push(`  Security Group: ${sg.name}`);
      lines.push(`    Display Name: ${title}`);
      lines.push(`    Description: ${description}`);
      if (sg.members?.members) {
        const memberNames = sg.members.members.map((m: any) => m.$refText).join(', ');
        lines.push(`    Members: ${memberNames}`);
      }
      lines.push('');
    }
    lines.push('*/');
    lines.push('');
  }

  // Collect retention labels
  const retentionLabels = (ast.statements ?? []).filter(
    (s: any) => s.$type === 'RetentionLabel'
  );

  if (retentionLabels.length > 0) {
    lines.push('// Retention Labels (Microsoft Purview)');
    lines.push('// Note: Retention label creation requires Compliance Center API');
    lines.push('// The following defines the label configuration');
    lines.push('var retentionLabels = [');
    for (const label of retentionLabels) {
      const title = label.title?.replace(/^["']|["']$/g, '') ?? label.name;
      const description = label.description?.replace(/^["']|["']$/g, '') ?? '';
      lines.push('  {');
      lines.push(`    name: '${label.name}'`);
      lines.push(`    displayName: '${title}'`);
      lines.push(`    description: '${description}'`);
      lines.push('  }');
    }
    lines.push(']');
    lines.push('');
  }

  // Collect sensitivity labels
  const sensitivityLabels = (ast.statements ?? []).filter(
    (s: any) => s.$type === 'SensitivityLabel'
  );

  if (sensitivityLabels.length > 0) {
    lines.push('// Sensitivity Labels (Microsoft Purview Information Protection)');
    lines.push('var sensitivityLabels = [');
    for (const label of sensitivityLabels) {
      const title = label.title?.replace(/^["']|["']$/g, '') ?? label.name;
      const description = label.description?.replace(/^["']|["']$/g, '') ?? '';
      lines.push('  {');
      lines.push(`    name: '${label.name}'`);
      lines.push(`    displayName: '${title}'`);
      lines.push(`    description: '${description}'`);
      lines.push('  }');
    }
    lines.push(']');
    lines.push('');
  }

  // Deployment script module reference
  lines.push('// Deployment Module');
  lines.push("module deployment 'modules/ecml-deployment.bicep' = {");
  lines.push("  name: 'ecml-deployment'");
  lines.push('  scope: rg');
  lines.push('  params: {');
  lines.push('    location: location');
  lines.push('    siteUrl: siteUrl');
  if (retentionLabels.length > 0) {
    lines.push('    retentionLabels: retentionLabels');
  }
  if (sensitivityLabels.length > 0) {
    lines.push('    sensitivityLabels: sensitivityLabels');
  }
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Outputs
  lines.push('// Outputs');
  lines.push('output resourceGroupName string = rg.name');
  lines.push('output resourceGroupId string = rg.id');

  return lines.join('\n');
}
