/**
 * Generate PowerShell Operation
 *
 * Generates PnP PowerShell scripts for deploying ECML content models
 * to SharePoint/Microsoft 365.
 *
 * @packageDocumentation
 */

import type { OperationHandler, OperationContext, OperationResult } from '@sanyam/types';

/**
 * Handler for generating PowerShell scripts from ECML models.
 */
export const generatePowerShellHandler: OperationHandler = async (
  context: OperationContext
): Promise<OperationResult> => {
  const { document, selectedIds } = context;
  const ast = document.parseResult.value as any;

  if (!ast) {
    return {
      success: false,
      error: 'Failed to parse document',
    };
  }

  // Generate PowerShell script
  const script = generateScript(ast, selectedIds);

  return {
    success: true,
    data: {
      script,
      language: 'powershell',
      fileName: `deploy-${getModelName(ast)}.ps1`,
    },
    message: 'PowerShell script generated successfully',
  };
};

/**
 * Generate the PowerShell script from the AST.
 */
function generateScript(ast: any, selectedIds?: readonly string[]): string {
  const lines: string[] = [];

  // Header
  lines.push('# Generated by ECML PowerShell Generator');
  lines.push(`# Model: ${getModelName(ast)}`);
  lines.push(`# Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('# Requires PnP.PowerShell module');
  lines.push('# Install-Module -Name PnP.PowerShell -Scope CurrentUser');
  lines.push('');
  lines.push('param(');
  lines.push('    [Parameter(Mandatory=$true)]');
  lines.push('    [string]$SiteUrl,');
  lines.push('    [Parameter(Mandatory=$false)]');
  lines.push('    [switch]$WhatIf');
  lines.push(')');
  lines.push('');
  lines.push('# Connect to SharePoint');
  lines.push('Connect-PnPOnline -Url $SiteUrl -Interactive');
  lines.push('');

  // Process statements
  const statements = ast.statements ?? [];
  for (const stmt of statements) {
    // Skip if we have selectedIds and this element isn't selected
    if (selectedIds && selectedIds.length > 0) {
      const elementId = stmt.$id ?? stmt.name;
      if (elementId && !selectedIds.includes(elementId)) {
        continue;
      }
    }

    const generated = generateStatementScript(stmt);
    if (generated) {
      lines.push(generated);
      lines.push('');
    }
  }

  // Footer
  lines.push('# Deployment complete');
  lines.push('Write-Host "Deployment complete!" -ForegroundColor Green');
  lines.push('');
  lines.push('# Disconnect');
  lines.push('Disconnect-PnPOnline');

  return lines.join('\n');
}

/**
 * Generate script for a single statement.
 */
function generateStatementScript(stmt: any): string | null {
  const type = stmt.$type;

  switch (type) {
    case 'Content':
      return generateContentScript(stmt);
    case 'SecurityGroup':
      return generateSecurityGroupScript(stmt);
    case 'RetentionLabel':
      return generateRetentionLabelScript(stmt);
    case 'SensitivityLabel':
      return generateSensitivityLabelScript(stmt);
    default:
      return `# TODO: ${type} "${stmt.name}" - not yet implemented`;
  }
}

function generateContentScript(stmt: any): string {
  const name = stmt.name ?? 'Untitled';
  const displayName = stmt.displayName ?? name;
  const description = stmt.description ?? '';

  return `# Create Content Type: ${displayName}
$contentType = Get-PnPContentType -Identity "${name}" -ErrorAction SilentlyContinue
if (-not $contentType) {
    if (-not $WhatIf) {
        Add-PnPContentType -Name "${name}" -Description "${description}" -Group "ECML Content Types"
        Write-Host "Created content type: ${name}" -ForegroundColor Green
    } else {
        Write-Host "[WhatIf] Would create content type: ${name}" -ForegroundColor Yellow
    }
} else {
    Write-Host "Content type already exists: ${name}" -ForegroundColor Cyan
}`;
}

function generateSecurityGroupScript(stmt: any): string {
  const name = stmt.name ?? 'Untitled';
  const displayName = stmt.displayName ?? name;
  const description = stmt.description ?? '';

  return `# Create Security Group: ${displayName}
$group = Get-PnPGroup -Identity "${name}" -ErrorAction SilentlyContinue
if (-not $group) {
    if (-not $WhatIf) {
        New-PnPGroup -Title "${name}" -Description "${description}"
        Write-Host "Created security group: ${name}" -ForegroundColor Green
    } else {
        Write-Host "[WhatIf] Would create security group: ${name}" -ForegroundColor Yellow
    }
} else {
    Write-Host "Security group already exists: ${name}" -ForegroundColor Cyan
}`;
}

function generateRetentionLabelScript(stmt: any): string {
  const name = stmt.name ?? 'Untitled';
  const displayName = stmt.displayName ?? name;

  return `# Note: Retention labels require Microsoft 365 Compliance Center
# Create Retention Label: ${displayName}
Write-Host "TODO: Configure retention label '${name}' in Compliance Center" -ForegroundColor Yellow`;
}

function generateSensitivityLabelScript(stmt: any): string {
  const name = stmt.name ?? 'Untitled';
  const displayName = stmt.displayName ?? name;

  return `# Note: Sensitivity labels require Microsoft 365 Information Protection
# Create Sensitivity Label: ${displayName}
Write-Host "TODO: Configure sensitivity label '${name}' in Information Protection" -ForegroundColor Yellow`;
}

function getModelName(ast: any): string {
  // Try to find model name from pragmas or use a default
  const pragmas = ast.pragmas ?? [];
  for (const pragma of pragmas) {
    if (pragma.name === 'model' && pragma.value) {
      return pragma.value;
    }
  }
  return 'ecml-model';
}
